# Generated by Django 5.2.17 on 2026-10-03 09:13

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, help_text='e.g. Talent Acquisition Lead, HR Manager, Founder', max_length=150, verbose_name='Designation / Job Title')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Department')),
                ('is_company_admin', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recruiter Profile',
                'verbose_name_plural': 'Recruiter Profiles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('job_seeker', 'Job Seeker'), ('recruiter', 'Recruiter / Employer'), ('admin', 'Administrator')], default='job_seeker', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919999999999' or '9999999999'. Up to 15 digits allowed.", regex='^\\+?[0-9]{10,15}$')], verbose_name='Phone Number')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/')),
                ('is_verified', models.BooleanField(default=False)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, help_text='e.g. Senior Django Developer | Python & AWS Specialist', max_length=255, verbose_name='Professional Headline')),
                ('summary', models.TextField(blank=True, help_text='A brief summary of your expertise, career goals, and key achievements.', verbose_name='Career Summary')),
                ('current_job_title', models.CharField(blank=True, max_length=150, verbose_name='Current Job Title')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='prefer_not_to_say', max_length=25, verbose_name='Gender')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('address', models.TextField(blank=True, verbose_name='Permanent / Residential Address')),
                ('preferred_location', models.CharField(blank=True, max_length=200, verbose_name='Preferred Work City/Region')),
                ('total_experience_years', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='Total Experience (Years)')),
                ('current_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Current CTC (in ₹ LPA)')),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Expected CTC (in ₹ LPA)')),
                ('notice_period_days', models.IntegerField(default=30, verbose_name='Notice Period (Days)')),
                ('work_preference', models.CharField(choices=[('any', 'Any Mode'), ('on_site', 'On-site / In-Office'), ('remote', 'Remote / Work from Home'), ('hybrid', 'Hybrid')], default='any', max_length=20, verbose_name='Work Preference')),
                ('skills_csv', models.TextField(blank=True, help_text='e.g. Python, Django, PostgreSQL, Docker, React, REST APIs', verbose_name='Key Skills (Comma-separated)')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn Profile URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub Profile URL')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Portfolio / Personal Website')),
                ('profile_views', models.PositiveIntegerField(default=0)),
                ('completion_percentage', models.PositiveSmallIntegerField(default=25)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Seeker Profile',
                'verbose_name_plural': 'Job Seeker Profiles',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company / Organization')),
                ('job_title', models.CharField(max_length=150, verbose_name='Job Title / Designation')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Job Location')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_current', models.BooleanField(default=False, verbose_name='I currently work here')),
                ('description', models.TextField(blank=True, verbose_name='Key Responsibilities & Achievements')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='accounts.jobseekerprofile')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text='e.g. B.Tech in Computer Science, BCA, MBA', max_length=150, verbose_name='Degree / Course')),
                ('institution', models.CharField(max_length=255, verbose_name='College / University / School')),
                ('field_of_study', models.CharField(blank=True, max_length=150, verbose_name='Field of Study / Specialization')),
                ('start_year', models.PositiveIntegerField(verbose_name='Starting Year')),
                ('end_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Completion Year / Expected')),
                ('grade', models.CharField(blank=True, max_length=50, verbose_name='Grade / Percentage / CGPA')),
                ('description', models.TextField(blank=True, verbose_name='Activities / Coursework')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='accounts.jobseekerprofile')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Certification Title')),
                ('issuing_organization', models.CharField(max_length=200, verbose_name='Issuing Organization')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('credential_id', models.CharField(blank=True, max_length=100, verbose_name='Credential ID')),
                ('credential_url', models.URLField(blank=True, verbose_name='Credential URL')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='accounts.jobseekerprofile')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Achievement Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='accounts.jobseekerprofile')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100, verbose_name='Language')),
                ('proficiency', models.CharField(choices=[('basic', 'Basic / Elementary'), ('conversational', 'Conversational'), ('fluent', 'Fluent / Professional'), ('native', 'Native / Bilingual')], default='fluent', max_length=30, verbose_name='Proficiency')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='accounts.jobseekerprofile')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Project Title')),
                ('technologies', models.CharField(blank=True, help_text='e.g. Python, Django, PostgreSQL, Bootstrap 5', max_length=255, verbose_name='Technologies Used')),
                ('project_url', models.URLField(blank=True, verbose_name='Project URL / GitHub Link')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('description', models.TextField(blank=True, verbose_name='Project Description & Highlights')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.jobseekerprofile')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-id'],
            },
        ),
    ]
