# Generated by Django 5.2.17 on 2026-10-03 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Company Name')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/%Y/', verbose_name='Company Logo')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='companies/covers/%Y/', verbose_name='Cover Image')),
                ('tagline', models.CharField(blank=True, max_length=255, verbose_name='Tagline / Punchline')),
                ('about', models.TextField(verbose_name='About Company')),
                ('industry', models.CharField(help_text='e.g. Information Technology, FinTech, E-Commerce', max_length=150, verbose_name='Industry / Sector')),
                ('company_size', models.CharField(choices=[('1-10', '1-10 Employees (Startup)'), ('11-50', '11-50 Employees (Small)'), ('51-200', '51-200 Employees (Medium)'), ('201-500', '201-500 Employees (Mid-Market)'), ('500+', '500+ Employees (Enterprise)')], default='51-200', max_length=30, verbose_name='Company Size')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year Founded')),
                ('website', models.URLField(blank=True, verbose_name='Company Website')),
                ('email', models.EmailField(max_length=254, verbose_name='Corporate Contact Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Corporate Phone')),
                ('city', models.CharField(max_length=100, verbose_name='Headquarters City')),
                ('state', models.CharField(max_length=100, verbose_name='Headquarters State')),
                ('address', models.TextField(blank=True, verbose_name='Office Address')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn Page')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter / X')),
                ('benefits', models.TextField(blank=True, help_text='e.g. Health Insurance, Flexible Hours, Annual Bonus, ESOPs', verbose_name='Perks & Benefits')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified Employer Badge')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Employer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, verbose_name='Rating')),
                ('title', models.CharField(max_length=200, verbose_name='Review Title')),
                ('pros', models.TextField(blank=True, verbose_name='Pros')),
                ('cons', models.TextField(blank=True, verbose_name='Cons')),
                ('review_text', models.TextField(verbose_name='Detailed Review')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Approved by Moderator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Review',
                'verbose_name_plural': 'Company Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'user')},
            },
        ),
    ]
