# Generated by Django 5.2.17 on 2026-10-03 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('icon', models.CharField(default='fa-solid fa-briefcase', help_text="e.g. 'fa-solid fa-laptop-code', 'fa-solid fa-chart-line'", max_length=100, verbose_name='FontAwesome Icon Class')),
                ('description', models.TextField(blank=True, verbose_name='Category Description')),
                ('is_featured', models.BooleanField(default=True, verbose_name='Featured on Homepage')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Job Category',
                'verbose_name_plural': 'Job Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Skill Name')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Django Jobs in Bangalore', max_length=150, verbose_name='Alert Name')),
                ('keywords', models.CharField(blank=True, max_length=200, verbose_name='Keywords / Skills')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Location / City')),
                ('job_type', models.CharField(blank=True, max_length=30, verbose_name='Job Type')),
                ('work_mode', models.CharField(blank=True, max_length=30, verbose_name='Work Mode')),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Salary (₹ LPA)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='jobs.jobcategory')),
            ],
            options={
                'verbose_name': 'Job Alert',
                'verbose_name_plural': 'Job Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Job Title')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Department')),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('freelance', 'Freelance'), ('contract', 'Contract')], default='full_time', max_length=30, verbose_name='Job Type')),
                ('work_mode', models.CharField(choices=[('on_site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='on_site', max_length=30, verbose_name='Work Mode')),
                ('location_city', models.CharField(max_length=100, verbose_name='Job City')),
                ('location_state', models.CharField(max_length=100, verbose_name='Job State')),
                ('experience_min', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='Minimum Experience (Years)')),
                ('experience_max', models.DecimalField(decimal_places=1, default=3.0, max_digits=4, verbose_name='Maximum Experience (Years)')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Salary (₹ LPA)')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximum Salary (₹ LPA)')),
                ('hide_salary', models.BooleanField(default=False, verbose_name='Hide salary from public job card (Competitive CTC)')),
                ('openings_count', models.PositiveIntegerField(default=1, verbose_name='Number of Openings')),
                ('description', models.TextField(verbose_name='Job Overview / Description')),
                ('responsibilities', models.TextField(blank=True, verbose_name='Key Responsibilities')),
                ('requirements', models.TextField(blank=True, verbose_name='Candidate Requirements & Qualifications')),
                ('benefits', models.TextField(blank=True, verbose_name='Perks, Benefits & Culture')),
                ('education_required', models.CharField(blank=True, help_text='e.g. B.E/B.Tech, BCA, MCA, Any Graduate', max_length=200, verbose_name='Education Qualification')),
                ('application_deadline', models.DateField(blank=True, null=True, verbose_name='Application Deadline')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='published', max_length=20, verbose_name='Status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Job Post')),
                ('is_fresher_friendly', models.BooleanField(default=False, verbose_name='Fresher Friendly (0 Experience)')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('saves_count', models.PositiveIntegerField(default=0)),
                ('applications_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='jobs.jobcategory')),
                ('skills', models.ManyToManyField(blank=True, related_name='jobs', to='jobs.skill')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100, verbose_name='State / UT')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('is_popular', models.BooleanField(default=False, verbose_name='Popular Hub')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['state', 'city'],
                'unique_together': {('state', 'city')},
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Job',
                'verbose_name_plural': 'Saved Jobs',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'job')},
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', '-created_at'], name='jobs_job_status_57b86b_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_type', 'work_mode'], name='jobs_job_job_typ_7d5cf7_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location_city', 'location_state'], name='jobs_job_locatio_7ef640_idx'),
        ),
    ]
