# Generated by Django 5.2.17 on 2026-10-03 09:13

import apps.resumes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Python Developer Resume', max_length=150, verbose_name='Resume Title / Label')),
                ('resume_type', models.CharField(choices=[('uploaded', 'Uploaded File (PDF / DOCX)'), ('builder', 'CareerHub Resume Builder')], default='uploaded', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/', validators=[apps.resumes.models.validate_resume_file])),
                ('template_name', models.CharField(choices=[('modern', 'Modern Elegant'), ('classic', 'Classic Corporate'), ('minimal', 'Minimalist Tech')], default='modern', max_length=50)),
                ('is_primary', models.BooleanField(default=False, verbose_name='Set as Primary Resume')),
                ('summary_override', models.TextField(blank=True, help_text='Customized summary specifically for this resume')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
