# Generated by Django 5.2.17 on 2026-10-03 09:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Plan Name')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price (₹ INR)')),
                ('billing_period', models.CharField(choices=[('monthly', 'Per Month'), ('yearly', 'Per Year'), ('one_time', 'One-Time')], default='monthly', max_length=20)),
                ('job_posting_limit', models.PositiveIntegerField(default=2, verbose_name='Job Posting Limit')),
                ('featured_job_limit', models.PositiveIntegerField(default=0, verbose_name='Featured Job Postings Limit')),
                ('candidate_contacts_limit', models.PositiveIntegerField(default=20, verbose_name='Candidate Direct Messages Limit')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Short Description')),
                ('features_list', models.TextField(help_text='e.g.\nPost up to 15 Active Jobs\n3 Featured Jobs on Homepage\nPriority Candidate Pipeline\nEmail Support', verbose_name='Key Features (One feature per line)')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Highlight as Most Popular')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='RecruiterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('active_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('jobs_posted_this_cycle', models.PositiveIntegerField(default=0)),
                ('featured_jobs_posted_this_cycle', models.PositiveIntegerField(default=0)),
                ('recruiter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_subscriptions', to='payments.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Recruiter Subscription',
                'verbose_name_plural': 'Recruiter Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=150, unique=True, verbose_name='Razorpay Order ID')),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=150, verbose_name='Razorpay Payment ID')),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, verbose_name='Razorpay Signature')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Paid (₹)')),
                ('currency', models.CharField(default='INR', max_length=10, verbose_name='Currency')),
                ('status', models.CharField(choices=[('created', 'Order Created'), ('success', 'Payment Successful'), ('failed', 'Payment Failed')], default='created', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
