# Generated by Django 5.2.17 on 2026-10-03 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('incorrect_company', 'Fraudulent / Impersonating Company'), ('spam', 'Spamming Applicants'), ('unethical', 'Unethical Hiring Practices'), ('other', 'Other Concern')], max_length=30, verbose_name='Reason for Reporting')),
                ('details', models.TextField(verbose_name='Details')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='companies.company')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Report',
                'verbose_name_plural': 'Company Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fake_job', 'Fake Job or Suspicious Posting'), ('incorrect_info', 'Incorrect / Inaccurate Information'), ('spam', 'Spam or Duplicate Listing'), ('scam', 'Asking for Money / Security Deposit Scam'), ('expired', 'Job Position Already Filled / Expired'), ('other', 'Other Violation')], max_length=30, verbose_name='Reason for Reporting')),
                ('details', models.TextField(verbose_name='Detailed Explanation')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('resolved', 'Action Taken / Resolved'), ('dismissed', 'Dismissed / False Alarm')], default='pending', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Moderation Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jobs.job')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Report',
                'verbose_name_plural': 'Job Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
