# Generated by Django 5.2.17 on 2026-10-03 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('video', 'Video Call (Online)'), ('phone', 'Phone / Telephonic Round'), ('in_person', 'In-Person (Office / On-site)')], default='video', max_length=20, verbose_name='Interview Type')),
                ('interview_date', models.DateField(verbose_name='Interview Date')),
                ('interview_time', models.TimeField(verbose_name='Interview Time')),
                ('meeting_url', models.URLField(blank=True, verbose_name='Meeting URL (Google Meet / Zoom / Teams)')),
                ('location_address', models.TextField(blank=True, help_text='Required for In-person rounds', verbose_name='Office / Venue Address')),
                ('interview_round', models.CharField(default='Technical Round', help_text='e.g. Technical Round 1, HR Discussion, Coding Challenge', max_length=100, verbose_name='Round Name')),
                ('notes', models.TextField(blank=True, verbose_name='Instructions for Candidate')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.jobapplication')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews_as_candidate', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.job')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
                'ordering': ['interview_date', 'interview_time'],
            },
        ),
    ]
