# Generated by Django 5.2.17 on 2026-10-03 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Notification Title')),
                ('message', models.TextField(verbose_name='Message Content')),
                ('notification_type', models.CharField(choices=[('application_submitted', 'Application Submitted'), ('application_status', 'Application Status Updated'), ('interview_scheduled', 'Interview Scheduled'), ('interview_updated', 'Interview Updated'), ('new_message', 'New Message Received'), ('payment_success', 'Payment Completed'), ('job_published', 'Job Published'), ('system', 'System Notification')], default='system', max_length=35)),
                ('link_url', models.CharField(blank=True, max_length=255, verbose_name='Destination Link')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
